version: '2.1'
services:
  fetch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
      - DB_PATH
      - INTERVAL
    volumes:
    - db:/usr/src/app/db
    command: node fetch.js
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
      - DB_PATH
      - SERVER_PORT
      - RATE_LIMIT_WINDOW
      - RATE_LIMIT
      - MEMCACHED_LOCATION
      - MEMCACHED_EXPIRATION
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - db:/usr/src/app/db
    command: node server.js
  memcached:
      image: memcached:alpine
      ports:
        - '11211:11211'
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
      - DB_PATH
    volumes:
      - db:/usr/src/app/db
    command: sh db.sh
  db-delete:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
      - DB_PATH
    volumes:
      - db:/usr/src/app/db
    command: rm $DB_PATH
  db-dump:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
      - DB_PATH
    volumes:
      - db:/usr/src/app/db
    command: sh dump.sh
volumes:
  db:
